# Generated by Django 3.2 on 2022-10-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='awb_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
    ]
