# Generated by Django 3.2 on 2022-10-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221002_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
