# Generated by Django 3.2 on 2022-11-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221108_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='delivery_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Scheduled', 'Scheduled'), ('Shipped', 'Shipped'), ('In_Progress', 'In_Progress')], default='In_Progress', max_length=100),
        ),
    ]
