# Generated by Django 3.2 on 2022-10-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'wallet'), ('card', 'card'), ('netbanking', 'netbanking'), ('emi', 'emi'), ('paypal', 'paypal'), ('cod', 'cod')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='dj', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='dj', max_length=255)),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='products.order')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
