# Generated by Django 3.2 on 2022-10-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_order_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
