# Generated by Django 3.2 on 2022-10-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'wallet'), ('card', 'card'), ('netbanking', 'netbanking'), ('emi', 'emi'), ('paypal', 'paypal'), ('cod', 'cod')], default='cod', max_length=50),
        ),
    ]
