# Generated by Django 3.2 on 2022-11-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
