# Generated by Django 3.2 on 2022-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='billing_city',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Banglore', 'Banglore'), ('Delhi', 'Dehli')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='billing_state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='shipping_city',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Banglore', 'Banglore'), ('Delhi', 'Dehli')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='shipping_state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat')], max_length=100),
        ),
    ]
